project:
  type: website
  output-dir: _site #this is default
  preview: 
    port: 4212
    browser: false
resources:
  - CNAME
website:
  title: "West End Statistics"
  favicon: favicon.png
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/vitallish/westendstats
      - icon: mastodon
        href: https://fosstodon.org/@vitaly_druker
format:
  html:
    theme: yeti
    css: styles.css

execute: 
  freeze: auto



